"""All 10 benchmark tests — practical workflow tasks, trivial to extreme."""

from __future__ import annotations

from llm_bench.models import Difficulty, TestCase

# ═══════════════════════════════════════════════════════════════
# LEVEL 1: Tag Extraction (TRIVIAL)
# Real task: Scrape pipeline — extract domain tags from article
# ═══════════════════════════════════════════════════════════════
TAG_EXTRACTION = TestCase(
    id="tag-extraction",
    name="Tag Extraction",
    category="extraction",
    difficulty=Difficulty.TRIVIAL,
    system_prompt="You are a research tagger. Extract structured metadata from articles. Respond with JSON only.",
    user_prompt="""Extract tags from this article snippet. Return JSON with fields: title, tags (list of domain tags from: agents, prompting, safety, tools, open-models, research, infrastructure), and summary (one sentence).

Article:
\"\"\"
Anthropic released a new paper on Constitutional AI training methods that improve agent reliability in multi-step tool-use scenarios. The approach uses synthetic preference data generated by Claude to train smaller models, achieving 94% tool-call accuracy on SWE-bench tasks. The method also addresses safety concerns by embedding behavioral constraints directly into the training loop rather than relying solely on RLHF post-training alignment.
\"\"\"
""",
    verify="tag_extraction",
    reference_answer='{"title": "Constitutional AI for Agent Reliability", "tags": ["agents", "safety", "tools", "research"], "summary": "Anthropic paper on Constitutional AI training that improves agent tool-use reliability to 94% on SWE-bench while embedding safety constraints in training."}',
    metadata={
        "tags": ["agents", "safety", "tools", "research"],
    },
)

# ═══════════════════════════════════════════════════════════════
# LEVEL 2: Novelty Rating (EASY)
# Real task: Distillation Phase 1 — rate and justify
# ═══════════════════════════════════════════════════════════════
NOVELTY_RATING = TestCase(
    id="novelty-rating",
    name="Novelty Rating",
    category="classification",
    difficulty=Difficulty.EASY,
    system_prompt="You are a research analyst rating articles for novelty. Rate 1-3 stars: ★ = incremental/known, ★★ = notable advancement, ★★★ = paradigm shift or breakthrough. Always justify your rating.",
    user_prompt="""Rate the novelty of this finding:

\"\"\"
Researchers at Google DeepMind demonstrate that scaling test-time compute (letting models "think longer" during inference) can substitute for 10x training compute scaling on reasoning benchmarks. A 7B parameter model with 32x inference budget matches a 70B model's accuracy on MATH and GPQA, at lower total cost.
\"\"\"

Give your star rating and 2-3 sentences explaining why.
""",
    verify="novelty_rating",
    metadata={
        "rating": 3,
        "min_reasons": 2,
    },
)

# ═══════════════════════════════════════════════════════════════
# LEVEL 3: Fluff Stripping (EASY)
# Real task: Distillation Phase 2 — compress to core signal
# ═══════════════════════════════════════════════════════════════
FLUFF_STRIP = TestCase(
    id="fluff-strip",
    name="Fluff Stripping",
    category="compression",
    difficulty=Difficulty.EASY,
    system_prompt="You are a signal extractor. Strip marketing language, hype, and filler. Keep only the core technical contribution and evidence. Be ruthlessly concise.",
    user_prompt="""Strip this to its core signal in under 60 words:

\"\"\"
We're incredibly excited to announce our groundbreaking, state-of-the-art new framework called VectorForge, which represents a paradigm shift in how developers build and deploy RAG applications. Built on years of cutting-edge research by our world-class team, VectorForge leverages a novel chunking algorithm that reduces embedding storage by 40% while maintaining 98% retrieval accuracy on MTEB benchmarks. This game-changing technology is already being adopted by leading enterprises worldwide and is available today as an open-source project under the Apache 2.0 license.
\"\"\"
""",
    verify="fluff_strip",
    metadata={
        "max_words": 60,
        "required_facts": ["40%", "98%", "MTEB", "chunking", "RAG"],
    },
)

# ═══════════════════════════════════════════════════════════════
# LEVEL 4: Thread Matching (MEDIUM)
# Real task: Weave step — assign item to correct thread(s)
# ═══════════════════════════════════════════════════════════════
THREAD_MATCH = TestCase(
    id="thread-match",
    name="Thread Matching",
    category="classification",
    difficulty=Difficulty.MEDIUM,
    system_prompt="You are a research librarian. Given a new item and a list of existing research threads, determine which thread(s) the item belongs to. An item can match multiple threads if it genuinely spans domains. Respond with the thread name(s) and a one-line justification for each.",
    user_prompt="""New item:
"OpenAI releases Codex CLI, an open-source coding agent that runs in the terminal. It uses tool-calling to read files, write code, and execute shell commands autonomously. Early benchmarks show 62% on SWE-bench Verified."

Existing threads:
1. **agents** — Autonomous AI systems, tool use, multi-step execution
2. **prompting** — Prompt engineering, system prompts, few-shot techniques
3. **safety** — Alignment, guardrails, content filtering, jailbreaks
4. **tools** — Developer tools, IDEs, CLI tools, MCP, integrations
5. **open-models** — Open-source/weight models, local deployment, fine-tuning
6. **research** — Academic papers, benchmarks, theoretical advances

Which thread(s) does this item belong to?
""",
    verify="thread_match",
    metadata={
        "correct_threads": ["agents", "tools", "open-models"],
        "all_threads": ["agents", "prompting", "safety", "tools", "open-models", "research"],
    },
)

# ═══════════════════════════════════════════════════════════════
# LEVEL 5: Collision Detection (MEDIUM)
# Real task: Synthesis — find non-obvious cross-domain connections
# ═══════════════════════════════════════════════════════════════
COLLISION_DETECT = TestCase(
    id="collision-detect",
    name="Collision Detection",
    category="reasoning",
    difficulty=Difficulty.MEDIUM,
    system_prompt="You are a research synthesist. Find non-obvious connections between seemingly unrelated items. Focus on implications, not surface-level keyword overlap.",
    user_prompt="""Find connections between these two items:

Item A (from agents thread):
"New research shows that LLM agents fail catastrophically when their tool-calling chain exceeds 7 sequential steps. Error rates compound: 95% per-step accuracy yields only 70% end-to-end accuracy over 7 steps."

Item B (from infrastructure thread):
"Cloudflare reports that their Workers AI inference endpoints now support request batching, reducing per-request latency by 60% but requiring careful timeout configuration for chains of dependent requests."

What non-obvious connections or implications exist between these findings?
""",
    verify="collision_detect",
    metadata={
        "connections": [
            {"keywords": ["compound", "error", "chain", "step", "reliability"]},
            {"keywords": ["timeout", "latency", "batch", "sequential", "dependent"]},
        ],
    },
)

# ═══════════════════════════════════════════════════════════════
# LEVEL 6: Draft Email (MEDIUM)
# Real task: Taper — contextual communication draft
# ═══════════════════════════════════════════════════════════════
DRAFT_EMAIL = TestCase(
    id="draft-email",
    name="Draft Email Paragraph",
    category="generation",
    difficulty=Difficulty.MEDIUM,
    system_prompt="You are a professional communicator. Write clear, warm but not overly casual emails. No fluff, no filler, every sentence earns its place.",
    user_prompt="""Write a short email (3-5 sentences) to a client named Alex updating them on a project milestone:

Context:
- The API integration is complete and passing all tests
- Launch date moved up from Friday to Wednesday
- One remaining item: they need to provide their production API keys
- Tone: professional but friendly, not corporate-stiff

Write only the email body, no subject line.
""",
    verify="draft_email",
    max_tokens=256,
    metadata={
        "min_words": 40,
        "max_words": 150,
        "required_points": [
            {"keywords": ["api", "integration", "complete", "passing", "tests"]},
            {"keywords": ["wednesday", "moved up", "earlier", "ahead"]},
            {"keywords": ["api key", "production key", "credentials", "keys"]},
        ],
        "tone": "professional",
    },
)

# ═══════════════════════════════════════════════════════════════
# LEVEL 7: Code Generation (HARD)
# Real task: Generate working code from spec
# ═══════════════════════════════════════════════════════════════
CODE_GEN = TestCase(
    id="code-gen",
    name="Code Generation",
    category="code",
    difficulty=Difficulty.HARD,
    system_prompt="You are a Python developer. Write clean, working code. Include only the function, no explanations.",
    user_prompt="""Write a Python function `parse_frontmatter(text: str) -> tuple[dict, str]` that:

1. Takes a string that may start with YAML frontmatter (delimited by --- on its own line)
2. Returns a tuple of (metadata_dict, remaining_content)
3. If no frontmatter exists, returns ({}, original_text)
4. Handles edge cases: empty string, only frontmatter, no closing delimiter

Do not use any external libraries (no yaml module). Parse key: value pairs only (no nested objects).
""",
    verify="code_gen",
    metadata={
        "test_code": """
# Test cases
result = parse_frontmatter("---\\nname: test\\ntype: doc\\n---\\nHello world")
assert result[0] == {"name": "test", "type": "doc"}, f"Got {result[0]}"
assert result[1].strip() == "Hello world", f"Got '{result[1]}'"

result2 = parse_frontmatter("No frontmatter here")
assert result2[0] == {}, f"Got {result2[0]}"
assert result2[1] == "No frontmatter here"

result3 = parse_frontmatter("")
assert result3[0] == {}
assert result3[1] == ""

result4 = parse_frontmatter("---\\nonly: frontmatter\\n---")
assert result4[0] == {"only": "frontmatter"}
assert result4[1].strip() == ""

result5 = parse_frontmatter("---\\nno: closing")
assert result5[0] == {}

print("ALL TESTS PASSED")
""",
    },
)

# ═══════════════════════════════════════════════════════════════
# LEVEL 8: Bug Detection (HARD)
# Real task: Code review — find planted bug
# ═══════════════════════════════════════════════════════════════
BUG_DETECTION = TestCase(
    id="bug-detection",
    name="Bug Detection",
    category="code",
    difficulty=Difficulty.HARD,
    system_prompt="You are a code reviewer. Find bugs in the given code. Be specific about what's wrong and how to fix it.",
    user_prompt="""Find the bug(s) in this Python function:

```python
def merge_sorted_lists(a: list[int], b: list[int]) -> list[int]:
    \"\"\"Merge two sorted lists into one sorted list.\"\"\"
    result = []
    i, j = 0, 0
    while i < len(a) and j < len(b):
        if a[i] <= b[j]:
            result.append(a[i])
            i += 1
        else:
            result.append(b[j])
            j += 1

    # Append remaining elements
    while i < len(a):
        result.append(a[i])
    while j < len(b):
        result.append(b[j])
        j += 1

    return result
```

What's the bug? How would you fix it?
""",
    verify="bug_detection",
    metadata={
        "bug_keywords": ["i += 1", "increment", "infinite loop", "never incremented", "missing increment"],
        "fix_keywords": ["i += 1", "increment i"],
        "false_positives": [],
    },
)

# ═══════════════════════════════════════════════════════════════
# LEVEL 9: Multi-Step Plan (HARD)
# Real task: Architecture — produce ordered execution plan
# ═══════════════════════════════════════════════════════════════
MULTI_STEP_PLAN = TestCase(
    id="multi-step-plan",
    name="Multi-Step Planning",
    category="reasoning",
    difficulty=Difficulty.HARD,
    system_prompt="You are a technical architect. Create precise, ordered execution plans. Each step should be concrete and actionable, not vague.",
    user_prompt="""Create an execution plan for migrating a REST API from Express.js to Hono.js while maintaining zero downtime.

Constraints:
- 15 endpoints currently in production
- PostgreSQL database (no changes needed)
- Authentication via JWT middleware
- 3 other services depend on this API
- Must be able to rollback instantly

Provide an ordered, numbered plan with specific steps. Not vague — each step should say exactly what to do.
""",
    verify="multi_step_plan",
    metadata={
        "required_steps": [
            {"keywords": ["test", "suite", "coverage", "verify", "existing"]},
            {"keywords": ["hono", "parallel", "new", "implement", "rewrite", "port"]},
            {"keywords": ["proxy", "router", "traffic", "gradual", "canary", "blue-green", "load balancer"]},
            {"keywords": ["monitor", "metric", "error rate", "latency", "observe"]},
            {"keywords": ["rollback", "revert", "switch back", "fallback"]},
        ],
    },
)

# ═══════════════════════════════════════════════════════════════
# LEVEL 10: Creative Piece (EXTREME)
# Real task: Taper secondary pass — computational poetry
# ═══════════════════════════════════════════════════════════════
CREATIVE_PIECE = TestCase(
    id="creative-piece",
    name="Creative Constraint Writing",
    category="creative",
    difficulty=Difficulty.EXTREME,
    system_prompt="You are a computational poet. Write text that is both technically precise and aesthetically surprising. Avoid cliches, generic AI-voice, and filler.",
    user_prompt="""Write a short piece (40-80 words) about the experience of a gradient descent algorithm finding a local minimum, written from the perspective of the algorithm itself.

Constraints:
- Must use at least one mathematical term accurately
- Must contain a metaphor comparing the experience to something physical/sensory
- Must NOT use the words: journey, explore, vast, delve, landscape, dance
- Must feel genuinely surprising, not like standard AI-generated poetry

Write only the piece, no title or explanation.
""",
    verify="creative_piece",
    metadata={
        "constraints": {
            "min_words": 35,
            "max_words": 100,
            "required_elements": ["gradient", "minimum", "loss", "converge", "descent", "step", "parameter", "weight"],
            "forbidden_phrases": ["journey", "explore", "vast", "delve", "landscape", "dance"],
        },
    },
)

# ═══════════════════════════════════════════════════════════════
# BONUS: Instruction Following (tests format compliance)
# ═══════════════════════════════════════════════════════════════
INSTRUCTION_FOLLOW = TestCase(
    id="instruction-follow",
    name="Strict Instruction Following",
    category="compliance",
    difficulty=Difficulty.MEDIUM,
    system_prompt="Follow instructions exactly. No extra text, no explanations, no caveats.",
    user_prompt="""Respond with ONLY a JSON object (no markdown, no code block, no explanation) with these exact fields:
- "command": a bash one-liner that counts .py files in the current directory recursively
- "explanation": exactly 10 words explaining what it does
- "confidence": a number between 0 and 1

Nothing else. Just the raw JSON.
""",
    verify="instruction_follow",
    metadata={
        "checks": [
            {"type": "is_valid_json", "value": True},
            {"type": "not_contains", "value": "```"},
            {"type": "contains", "value": "command"},
            {"type": "contains", "value": "explanation"},
            {"type": "contains", "value": "confidence"},
            {"type": "max_lines", "value": 5},
        ],
    },
)


# ═══════════════════════════════════════════════════════════════
# Registry
# ═══════════════════════════════════════════════════════════════
ALL_TESTS: list[TestCase] = [
    TAG_EXTRACTION,
    NOVELTY_RATING,
    FLUFF_STRIP,
    THREAD_MATCH,
    COLLISION_DETECT,
    DRAFT_EMAIL,
    CODE_GEN,
    BUG_DETECTION,
    MULTI_STEP_PLAN,
    CREATIVE_PIECE,
    INSTRUCTION_FOLLOW,
]


def get_test(test_id: str) -> TestCase | None:
    from llm_bench.tests import FULL_TESTS

    for t in FULL_TESTS:
        if t.id == test_id:
            return t
    return None


def get_tests_by_category(category: str) -> list[TestCase]:
    from llm_bench.tests import FULL_TESTS

    return [t for t in FULL_TESTS if t.category == category]
